Models/SummaryModels/CostCalculator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeliveryApp1
{
    public class CostCalculator
    {

        private static int GetDistance(string pickupAddress, string receiverAddress)
        {
            return 100;

        }

        /// <summary>
        /// 
        /// Get Cost of Delivery
        /// </summary>
        /// <param name="weight">Accepts weight in KG</param>
        /// <param name="pickupAddress">Full Address of Sender</param>
        /// <param name="receiverAddress">Full Address of Receiver</param>
        /// <returns>Return Cost of Delivery charge in Decimal Based on Weight and distance</returns>
        public static int GetCost(int item, int weight, string pickupAddress, string receiverAddress)
        {
            //int multiplier = 0;

            //int distance = GetDistance(pickupAddress, receiverAddress);
            //if (distance < 100) { multiplier = 20; }
            //else if (distance < 500) { multiplier = 50; }
            //else if (distance > 500) { multiplier = 100; }

            //return multiplier * weight;

            return item * weight;

        }

    }
}

Models/SummaryModels/OrderDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeliveryApp1.Models
{
    public class OrderDetailModel
    {
        public int OrderId { get; set; }

        public int ItemCount { get; set; }

        public int OrderWeight { get; set; }

        public string ReceiverAddress { get; set; }
        public string PickupAddress { get; set; }

        public int Cost { get; set; }

        public bool? isPaymentDone { get; set; }

        public int Getcost
        {
            get
            {

                return CostCalculator.GetCost(ItemCount, OrderWeight, PickupAddress, ReceiverAddress);

            }
            private set { }

        }
    }
}

Models/SummaryModels/PaymentModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeliveryApp1.Models
{
    public class PaymentModel
    {
        public int PaymentId { get; set; }
        public string OrderId { get; set; }
        public int Amount { get; set; }
        public DateTime CreatedDate { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeliveryApp1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/OrderSummaryController.cs
using DeliveryApp1.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeliveryApp1.Controllers
{
    public class OrderSummaryController : Controller
    {
        // GET: OrderSummary
        public ActionResult NewOrder(string id)
        {

            OrderDetailModel model = new OrderDetailModel()
            {
                OrderId = 1,
                ItemCount = 100

            };

            return View(model);
        }

        public ActionResult Summary(string orderId)

        {
            OrderDetailModel order = new OrderDetailModel();
            //{
            //Hardcoding for now
            order.OrderId = 1;
            order.ItemCount = 100;
            order.OrderWeight = 11;
            order.Cost = order.Getcost;

            //DataRow dr = DbHandler.GetInstance().GetOrderSummary(Convert.ToInt32(orderId));
            //OrderDetailModel order = new OrderDetailModel()
            //{
            //    ItemCount = Convert.ToInt32(dr[1]),
            //    OrderWeight = Convert.ToInt32(dr[2]),
            //    ReceiverAddress = Convert.ToString(dr[3]),
            //    PickupAddress = Convert.ToString(dr[4]),
            //    isPaymentDone = Convert.ToInt32(dr[5]) > 0 ? true : false,

            //};
            //Update Cost to Database
            //order.Cost = order.Getcost;
            // DbHandler.GetInstance().UpdateCost(Convert.ToInt32(orderId), order.Cost);

            return View(order);
        }

        [HttpGet]
        public ActionResult Payment(int id)
        {
            //  int amount = Dbhandler.getInstance().GetAmountbyId(id);
            PaymentModel payment = new PaymentModel()
            {
                Amount = id,
                OrderId = "ID500"

            };
            return View(payment);
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/OrderSummary/Home.cshtml
 
@{
    ViewBag.Title = "Home";
}

<h2>Home</h2>

Views/OrderSummary/NewOrder.cshtml
@model DeliveryApp1.Models.OrderDetailModel

@{
    ViewBag.Title = "NewOrder";
}

<h2>NewOrder</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken() 

    <div class="form-horizontal">
        <h4>OrderDetailModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.OrderId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderWeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderWeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderWeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReceiverAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReceiverAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReceiverAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PickupAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PickupAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PickupAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Getcost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Getcost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Getcost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @{
                    Session["ID"] = Model.OrderId;
                }
                @Html.ActionLink("Submit", "Summary", "OrderSummary", new { id = Model.OrderId }) 
            </div>
        </div>
    </div>
}

<div>
   
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/OrderSummary/Payment.cshtml
@{
    ViewBag.Title = "Payment";
}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
            font-family: Arial;
            font-size: 17px;
            padding: 8px;
        }

        * {
            box-sizing: border-box;
        }

        .row {
            display: -ms-flexbox; /* IE10 */
            display: flex;
            -ms-flex-wrap: wrap; /* IE10 */
            flex-wrap: wrap;
            margin-top: 30px;
        }

        .col-25 {
            -ms-flex: 25%; /* IE10 */
            flex: 25%;
        }

        .col-50 {
            -ms-flex: 50%; /* IE10 */
            flex: 50%;
        }

        .col-75 {
            -ms-flex: 75%; /* IE10 */
            flex: 75%;
        }

        .col-25,
        .col-50,
        .col-75 {
            padding: 0 16px;
        }

        input[type=text] {
            width: 100%;
            margin-bottom: 20px;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        label {
            margin-bottom: 10px;
            display: block;
        }

        .icon-container {
            margin-bottom: 20px;
            padding: 7px 0;
            font-size: 24px;
        }

        .btn {
            background-color: #04AA6D;
            color: white;
            padding: 12px;
            margin: 10px 0;
            border: none;
            width: 100%;
            border-radius: 3px;
            cursor: pointer;
            font-size: 17px;
        }

            .btn:hover {
                background-color: #45a049;
            }

        a {
            color: #2196F3;
        }

        hr {
            border: 1px solid lightgrey;
        }

        span.price {
            float: right;
            color: grey;
        }

        /* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (also change the direction - make the "cart" column go on top) */
        .col-25 {
            margin-bottom: 20px;
        }

        .PaymentInfo {
            color: seagreen;
            font: 700;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 17px;
            margin-right: 35px;
        }

        .PaymentHeder {
            margin-top: 50px;
        }
    </style>
</head>
<body>

    <div class="row">
        <div class="col-75">
            <div class="container">
                @using (Html.BeginForm("Home", "OrderDetail", FormMethod.Post))
                {
                    <div class="row">

                        <label for="fname">Amount:</label>
                        <label class="PaymentInfo">
                            &#x20b9; @Model.Amount
                        </label>

                        <div class="col-50">
                            <label for="cname">Name on Card</label>
                            <input type="text" id="cname" name="cardname" placeholder="First Name Last Name">

                            <label for="ccnum">Credit card number</label>
                            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
                            <label for="expmonth">Expiry</label>
                            <input type="month" min="2022-01" value="2024-01" id="expmonth" name="expmonth">

                            <label for="cvv">CVV</label>
                            <input type="text" id="cvv" name="cvv" placeholder="352">

                            <input type="submit" value="Pay" class="btn">

                        </div>
                    </div>
                }

            </div>
        </div>
    </div>

</body>
</html>

Views/OrderSummary/Summary.cshtml
@model DeliveryApp1.Models.OrderDetailModel

@{
    ViewBag.Title = "Summary";
}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css"  href="~/Content/SummaryStyleSheet.css" />
   
</head>
<body>
    <h4>Order Summary</h4>
    <div >

        <table class="table-bordered" >
            <tr>
                <td   >
                    <label> @Html.Label("Number of Itmes ")</label>
                </td>

                <td >
                   @Html.DisplayFor(model => model.ItemCount)
                </td>
            </tr>

            <tr>
                <td  >
                    <label>@Html.Label("Weight ")</label>
                </td>

                <td  >
                     @Html.DisplayFor(model => model.OrderWeight)
                </td>
            </tr>

            <tr>
                <td  >
                    @Html.Label("Receiver Address ")
                </td>

                <td  >
                    @Html.DisplayFor(model => model.ReceiverAddress)
                </td>
            </tr>

            <tr>
                <td  >
                    @Html.Label("Pickup Address ")
                </td>

                <td >
                    @Html.DisplayFor(model => model.PickupAddress)
                </td>
            </tr>

            <tr>
                <td  >
                    @Html.Label("Total Cost ")
                </td>

                <td  >
                    @Html.DisplayFor(model => model.Cost)
                </td>
            </tr>
        </table>

    </div>
    <div>
        @*<NewOrder> will be replaced with the controller name of new order team*@
        <button class="btn1" > @Html.ActionLink("Edit", "NewOrder", new { id = Model.OrderId }) </button> 
</div>
    <div><button class="btn"> @Html.ActionLink("Make Payment", "Payment", new { id = Model.Cost }) </button>
    </div>

</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Swiggy Genie</title>

    <style>
        a{
            color:white;
            text-decoration:none;
        }
      li{
          color:white;
          background-color:black;
      }
        li:hover {
            background-color: #04AA6D;
        }
      
    </style>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Swiggy Geine", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Swiggy Genie</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>